name: armpicom toc generator
on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
jobs:
  generateTOC:
    name: armpicom toc generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
